name: governance v4 auto

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

concurrency:
  group: governance-v4-auto
  cancel-in-progress: true

permissions:
  contents: write
  actions: read
  packages: read

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run governance
        run: |
          python scripts/governance_v4_auto.py

      - name: Commit state if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add STATE || true
          git diff --cached --quiet || git commit -m "auto: governance v4 state update"
          git push
